//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NintendoStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesEntities : DbContext
    {
        public GamesEntities()
            : base("name=GamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NintendoCategory> NintendoCategories { get; set; }
        public virtual DbSet<NintendoEmployee> NintendoEmployees { get; set; }
        public virtual DbSet<NintendoProduct> NintendoProducts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
