//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NintendoStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NintendoProduct
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Please enter a valid product name.")]
        [StringLength(25, ErrorMessage = "You cannot exceed 25 characeters.")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Please enter a valid image url.")]
        public string Picture { get; set; }
        [Required(ErrorMessage = "Please enter a valid description.")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please enter a valid price.")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Incorrect category selection.")]
        public Nullable<int> CategoryId { get; set; }
    
        public virtual NintendoCategory NintendoCategory { get; set; }
    }
}
