//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NintendoStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NintendoEmployee
    {
        public int StaffId { get; set; }
        [Required(ErrorMessage = "Please enter a valid name.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a valid email.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a valid position.")]
        public string Position { get; set; }
        [Required(ErrorMessage = "Please enter a valid description.")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please enter a valid image url.")]
        public string Profilepic { get; set; }
    }
}
